


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author shitaichen
 */
public class testUI extends javax.swing.JFrame {

    /**
     * Creates new form testUI
     */
    public testUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        map = new region();
        check = new javax.swing.JCheckBox();
        select4 = new javax.swing.JButton();
        select5 = new javax.swing.JButton();
        select6 = new javax.swing.JButton();
        select7 = new javax.swing.JButton();
        select8 = new javax.swing.JButton();
        select9 = new javax.swing.JButton();
        select10 = new javax.swing.JButton();
        select11 = new javax.swing.JButton();
        select12 = new javax.swing.JButton();
        select13 = new javax.swing.JButton();
        select14 = new javax.swing.JButton();
        select15 = new javax.swing.JButton();
        select16 = new javax.swing.JButton();
        select3 = new javax.swing.JToggleButton();
        select2 = new javax.swing.JButton();
        select1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        map.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout mapLayout = new javax.swing.GroupLayout(map);
        map.setLayout(mapLayout);
        mapLayout.setHorizontalGroup(
            mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        mapLayout.setVerticalGroup(
            mapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );

        check.setText("show all lions and ponds");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        select4.setText("region4");
        select4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select4ActionPerformed(evt);
            }
        });

        select5.setText("region5");
        select5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select5ActionPerformed(evt);
            }
        });

        select6.setText("region6");
        select6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select6ActionPerformed(evt);
            }
        });

        select7.setText("region7");
        select7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select7ActionPerformed(evt);
            }
        });

        select8.setText("region8");
        select8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select8ActionPerformed(evt);
            }
        });

        select9.setText("region9");
        select9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select9ActionPerformed(evt);
            }
        });

        select10.setText("region10");
        select10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select10ActionPerformed(evt);
            }
        });

        select11.setText("region11");
        select11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select11ActionPerformed(evt);
            }
        });

        select12.setText("reigon12");
        select12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select12ActionPerformed(evt);
            }
        });

        select13.setText("region13");
        select13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select13ActionPerformed(evt);
            }
        });

        select14.setText("region14");
        select14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select14ActionPerformed(evt);
            }
        });

        select15.setText("region15");
        select15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select15ActionPerformed(evt);
            }
        });

        select16.setText("region16");
        select16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select16ActionPerformed(evt);
            }
        });

        select3.setText("region3");
        select3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select3ActionPerformed(evt);
            }
        });

        select2.setText("region2");
        select2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select2ActionPerformed(evt);
            }
        });

        select1.setText("region1");
        select1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(map, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(select16, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(select15, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(check)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(select14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(select4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(select5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(select6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(select7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(select8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(select9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(select10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(select11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(select12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(select13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(select3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(select2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(select1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(check)
                .addGap(24, 24, 24)
                .addComponent(select1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(select2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(select3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(select4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(select5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(select6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(select7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(select8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(select9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(select10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(select11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(select12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(select13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(select14)
                    .addComponent(select15)
                    .addComponent(select16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(map, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void select4ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    	if(evt.getSource()==select4){
            //container.add(panel3,BorderLayout.CENTER);     	       
   		 ((region) map).startDynamic_4();
            setVisible(true);
        }
    }                                       

    private void select8ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    	if(evt.getSource()==select8){
            //container.add(panel3,BorderLayout.CENTER);     	       
   		 ((region) map).startDynamic_8();
            setVisible(true);
        }
    }                                       

    private void select12ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	if(evt.getSource()==select12){
            //container.add(panel3,BorderLayout.CENTER);     	       
   		 ((region) map).startDynamic_12();
            setVisible(true);
        }
    }                                        

    private void select1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    	 if(evt.getSource()==select1){
             //container.add(panel3,BorderLayout.CENTER);     	       
    		 ((region) map).startDynamic_1();
             setVisible(true);
         }
    }                                       

    private void select2ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    	if(evt.getSource()==select2){
            //container.add(panel3,BorderLayout.CENTER);     	       
   		 ((region) map).startDynamic_2();
            setVisible(true);
        }
    	
    }                                       

    private void select3ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    	if(evt.getSource()==select3){
            //container.add(panel3,BorderLayout.CENTER);     	       
   		 ((region) map).startDynamic_3();
            setVisible(true);
        }
    }                                       

    private void select5ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    	if(evt.getSource()==select5){
            //container.add(panel3,BorderLayout.CENTER);     	       
   		 ((region) map).startDynamic_5();
            setVisible(true);
        }
    }                                       

    private void select6ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    	if(evt.getSource()==select6){
            //container.add(panel3,BorderLayout.CENTER);     	       
   		 ((region) map).startDynamic_6();
            setVisible(true);
        }
    }                                       

    private void select7ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    	if(evt.getSource()==select7){
            //container.add(panel3,BorderLayout.CENTER);     	       
   		 ((region) map).startDynamic_7();
            setVisible(true);
        }
    }                                       

    private void select9ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    	if(evt.getSource()==select9){
            //container.add(panel3,BorderLayout.CENTER);     	       
   		 ((region) map).startDynamic_9();
            setVisible(true);
        }
    }                                       

    private void select10ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	if(evt.getSource()==select10){
            //container.add(panel3,BorderLayout.CENTER);     	       
   		 ((region) map).startDynamic_10();
            setVisible(true);
        }
    }                                        

    private void select11ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	if(evt.getSource()==select11){
            //container.add(panel3,BorderLayout.CENTER);     	       
   		 ((region) map).startDynamic_11();
            setVisible(true);
        }
    }                                        

    private void select13ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	if(evt.getSource()==select13){
            //container.add(panel3,BorderLayout.CENTER);     	       
   		 ((region) map).startDynamic_13();
            setVisible(true);
        }
    }                                        

    private void select14ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	if(evt.getSource()==select14){
            //container.add(panel3,BorderLayout.CENTER);     	       
   		 ((region) map).startDynamic_14();
            setVisible(true);
        }
    }                                        

    private void select15ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	if(evt.getSource()==select15){
            //container.add(panel3,BorderLayout.CENTER);     	       
   		 ((region) map).startDynamic_15();
            setVisible(true);
        }
    }                                        

    private void select16ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	if(evt.getSource()==select16){
            //container.add(panel3,BorderLayout.CENTER);     	       
   		 ((region) map).startDynamic_16();
            setVisible(true);
        }
    }                                        

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    	if(evt.getSource()==check){
            //container.add(panel3,BorderLayout.CENTER);     	       
    			((region) map).set_start();
    		setVisible(true);
        }
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JCheckBox check;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel map;
    private javax.swing.JButton select1;
    private javax.swing.JButton select10;
    private javax.swing.JButton select11;
    private javax.swing.JButton select12;
    private javax.swing.JButton select13;
    private javax.swing.JButton select14;
    private javax.swing.JButton select15;
    private javax.swing.JButton select16;
    private javax.swing.JButton select2;
    private javax.swing.JToggleButton select3;
    private javax.swing.JButton select4;
    private javax.swing.JButton select5;
    private javax.swing.JButton select6;
    private javax.swing.JButton select7;
    private javax.swing.JButton select8;
    private javax.swing.JButton select9;
    // End of variables declaration                   
}
